# Generated by Django 3.1.7 on 2021-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210403_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
